name: geo
channels:
  - conda-forge
dependencies:
  - python=3.12
  - gdal
  - rasterio
  - rioxarray
  - geopandas
  - pyogrio
  - pyarrow
  - pystac-client
  - shapely
  - numpy
  - pandas
  - scipy
  - scikit-image
  - matplotlib
  - tqdm
  - jupyterlab
